export const SET_STORY_NAME = "SET_STORY_NAME";
export const SET_STORY_DESCRIPTION = "SET_STORY_DESCRIPTION";
export const SET_STORY_IS_PRIVATE = "SET_STORY_IS_PRIVATE";
export const ADD_STORY_SLIDE = "ADD_STORY_SLIDE";
export const DELETE_STORY_SLIDE = "DELETE_STORY_SLIDE";
export const SET_STORY_SLIDE = "SET_STORY_SLIDE";
